# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Run Cypress BDD Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: cypress/included:14.3.1
      # Use the Cypress version matching your project (13.15.0 is the latest as of Apr 2025)

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache node_modules to speed up the workflow
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install Node.js dependencies
      - name: Install dependencies
        run: npm ci

      # Run Cypress BDD tests
      - name: Run Cypress tests
        run: npm test
        env:
          CI: true
          HOME: /root
          # Optional: Add Cypress Cloud record key for test recording
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # Upload test artifacts (reports, screenshots, videos) on failure
      - name: Upload test artifacts
        # if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/reports/
            cypress/screenshots/
            cypress/videos/
          retention-days: 30
